//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAWebApp.WebService1Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService1Reference.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOAWebApp.WebService1Reference.Contact[] Select(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAWebApp.WebService1Reference.Contact[]> SelectAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Insert(SOAWebApp.WebService1Reference.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task InsertAsync(SOAWebApp.WebService1Reference.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Update(SOAWebApp.WebService1Reference.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task UpdateAsync(SOAWebApp.WebService1Reference.Contact contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(string id);
        
        // CODEGEN: 消息 CustomSoapHeaderTestRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomSoapHeaderTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOAWebApp.WebService1Reference.CustomSoapHeaderTestResponse CustomSoapHeaderTest(SOAWebApp.WebService1Reference.CustomSoapHeaderTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomSoapHeaderTest", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAWebApp.WebService1Reference.CustomSoapHeaderTestResponse> CustomSoapHeaderTestAsync(SOAWebApp.WebService1Reference.CustomSoapHeaderTestRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Contact : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string nameField;
        
        private string phoneNoField;
        
        private string emailAddressField;
        
        private string addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PhoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
                this.RaisePropertyChanged("PhoneNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomSoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
                this.RaisePropertyChanged("PassWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomSoapHeaderTest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CustomSoapHeaderTestRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SOAWebApp.WebService1Reference.CustomSoapHeader CustomSoapHeader;
        
        public CustomSoapHeaderTestRequest() {
        }
        
        public CustomSoapHeaderTestRequest(SOAWebApp.WebService1Reference.CustomSoapHeader CustomSoapHeader) {
            this.CustomSoapHeader = CustomSoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomSoapHeaderTestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CustomSoapHeaderTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string CustomSoapHeaderTestResult;
        
        public CustomSoapHeaderTestResponse() {
        }
        
        public CustomSoapHeaderTestResponse(string CustomSoapHeaderTestResult) {
            this.CustomSoapHeaderTestResult = CustomSoapHeaderTestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : SOAWebApp.WebService1Reference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<SOAWebApp.WebService1Reference.WebService1Soap>, SOAWebApp.WebService1Reference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public SOAWebApp.WebService1Reference.Contact[] Select(string id) {
            return base.Channel.Select(id);
        }
        
        public System.Threading.Tasks.Task<SOAWebApp.WebService1Reference.Contact[]> SelectAsync(string id) {
            return base.Channel.SelectAsync(id);
        }
        
        public void Insert(SOAWebApp.WebService1Reference.Contact contact) {
            base.Channel.Insert(contact);
        }
        
        public System.Threading.Tasks.Task InsertAsync(SOAWebApp.WebService1Reference.Contact contact) {
            return base.Channel.InsertAsync(contact);
        }
        
        public void Update(SOAWebApp.WebService1Reference.Contact contact) {
            base.Channel.Update(contact);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(SOAWebApp.WebService1Reference.Contact contact) {
            return base.Channel.UpdateAsync(contact);
        }
        
        public void Delete(string id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string id) {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAWebApp.WebService1Reference.CustomSoapHeaderTestResponse SOAWebApp.WebService1Reference.WebService1Soap.CustomSoapHeaderTest(SOAWebApp.WebService1Reference.CustomSoapHeaderTestRequest request) {
            return base.Channel.CustomSoapHeaderTest(request);
        }
        
        public string CustomSoapHeaderTest(SOAWebApp.WebService1Reference.CustomSoapHeader CustomSoapHeader) {
            SOAWebApp.WebService1Reference.CustomSoapHeaderTestRequest inValue = new SOAWebApp.WebService1Reference.CustomSoapHeaderTestRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            SOAWebApp.WebService1Reference.CustomSoapHeaderTestResponse retVal = ((SOAWebApp.WebService1Reference.WebService1Soap)(this)).CustomSoapHeaderTest(inValue);
            return retVal.CustomSoapHeaderTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAWebApp.WebService1Reference.CustomSoapHeaderTestResponse> SOAWebApp.WebService1Reference.WebService1Soap.CustomSoapHeaderTestAsync(SOAWebApp.WebService1Reference.CustomSoapHeaderTestRequest request) {
            return base.Channel.CustomSoapHeaderTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAWebApp.WebService1Reference.CustomSoapHeaderTestResponse> CustomSoapHeaderTestAsync(SOAWebApp.WebService1Reference.CustomSoapHeader CustomSoapHeader) {
            SOAWebApp.WebService1Reference.CustomSoapHeaderTestRequest inValue = new SOAWebApp.WebService1Reference.CustomSoapHeaderTestRequest();
            inValue.CustomSoapHeader = CustomSoapHeader;
            return ((SOAWebApp.WebService1Reference.WebService1Soap)(this)).CustomSoapHeaderTestAsync(inValue);
        }
    }
}
