//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItcastOA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_UserInfo_ActionInfo
    {
        public long Id { get; set; }
        public long UserInfoID { get; set; }
        public long ActionInfoID { get; set; }
        public bool IsPass { get; set; }
    
        public virtual ActionInfo ActionInfo { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
